name: Debug Repo Structure

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: List root directory
        run: dir

      - name: List src folder
        run: dir src

      - name: List MH.Utils folder
        run: dir src\MH.Utils

      - name: List MH.Utils src folder
        run: dir src\MH.Utils\src
