name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: List files
      run: dir

    - name: List files 2
      run: dir src/MH.Utils

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/MH.Utils/MH.Utils.csproj

    - name: Build
      run: dotnet build src/MH.Utils/MH.Utils.csproj --configuration Release
    
    - name: Pack
      run: dotnet pack src/MH.Utils/MH.Utils.csproj --configuration Release --output nupkg

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
